spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://120.78.75.230:3306/ar_animal?rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 2577715138qwer
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    host: 120.78.75.230
    password: 2577715138qwer
    port: 6379
    jedis:
      pool:
        #设置最大连接数（负值表示没有限制）、最大阻塞时间（负值表示没有限制）、最大空闲连接、最小空闲连接
        max-active: 1000
        max-wait: -1ms
        max-idle: 999
        min-idle: 0
    lettuce:
      shutdown-timeout: 20000ms
      #设置超时连接时间
    timeout: 1800000

shiro-redis:
  enabled: true
  redis-manager:
    host: 120.78.75.230:6379
    password: 2577715138qwer

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml          #扫描 Mapper 映射文件
  type-aliases-package: com.guangtou.rareanimal_backstage.pojo.entity
  global-config:
    db-config:
      table-prefix: t_

shiro:
  loginUrl: /login/loginAdminer

rareanimal:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: token

ftp:
  host: 120.78.75.230
  userName: root
  password: 2577715138qweR
  port: 22
  # 图片服务器的存储的图片路径根目录
  rootPath: /usr/local/nginx/image
  timeout: 500000
  img:
    url: http://120.78.75.230:80     # ftp.img.url 为了上传文件成功后返回文件路径

server:
  port: 9090
